name: Docker Hardener Test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  harden:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 🔒 Run Docker Image Hardener
        uses: developer9508/docker-image-hardener-action@main
        with:
          dockerfile: examples/sample.Dockerfile
          scan: true
          summary: true
          save-json: true
          fail-on-critical: true
          severity: HIGH,CRITICAL

