name: Test Docker Hardener

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Docker Hardener
        uses: developer9508/docker-image-hardener-action@main
        with:
          dockerfile: examples/sample.Dockerfile
          scan: true
          save-json: true
          summary: true
          fail-on-critical: true
